version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: codedeploy_scripts/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy_scripts/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy_scripts/stop.sh
      timeout: 300
      runas: root