version: '3'
services:
  app:
    environment:
      - ENV=production
      - REDISURL=numbuyer-elasticache-cluster.d6jx2f.ng.0001.apne1.cache.amazonaws.com:6379
      - ALLOWORIGIN=https://practical-kirch-5024e4.netlify.app
      - LOGLEVEL=debug
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
        - "443:8001"
    tty: true
    volumes:
      - .:/go/src/work
  # SSL証明書の更新時検証ファイルの置き場のために使用
  httpd:
    image: "httpd:latest"
    ports:
        - "80:80"
    volumes:
        - "./ssl/docs:/usr/local/apache2/htdocs"