version: '3'
services:
  app:
    environment:
      - REDISURL=redis:6379
      - ALLOWORIGIN=https://practical-kirch-5024e4.netlify.app
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
        - "80:8001"
        - "443:8001"
    tty: true
    volumes:
      - .:/go/src/work
  redis:
    image: "redis:latest"
    ports:
        - "6379:6379"
    volumes:
        - "./data/redis:/data"