version: '3'
services:
  app:
    environment:
      - ENV=develop
      - REDISURL=redis:6379
      - ALLOWORIGIN=http://localhost:3000
      - LOGLEVEL=debug
    build: .
    ports:
        - "8000:8001"
    tty: true
    volumes:
      - .:/go/src/work
  redis:
    image: "redis:latest"
    ports:
        - "6379:6379"
    volumes:
        - "./data/redis:/data"