version: '3'
services:
  app:
    build: .
    ports:
        - "8000:8000"
    tty: true
    volumes:
      - .:/go/src/work
  redis:
    image: "redis:latest"
    ports:
        - "6379:6379"
    volumes:
        - "./data/redis:/data"