version: '3'
services:
  app:
    environment:
      - ENV=production
      - REDISURL=numbuyer-elasticache-cluster.d6jx2f.ng.0001.apne1.cache.amazonaws.com:6379
      - ALLOWORIGIN=https://practical-kirch-5024e4.netlify.app
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
        - "8000:8001"
    tty: true
    volumes:
      - .:/go/src/work